[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Viteza pentru Serial Monitor (UART)
monitor_speed = 9600
monitor_port = COM11
; Biblioteca pentru senzorul ultrasonic
lib_deps =
    teckel12/NewPing @ ^1.9.7

monitor_filters = send_on_enter, debug
monitor_echo = yes
monitor_eol = LF